### ISSUE TITLE
<CLASS DOES NOT EXIST>

### ISSUE THREAD

**Issue by rcemper** [diashenrique/iris-kaggle-socrata-generator#1]
following tst guide
````
IRISAPP>set api = ##class(dc.dataset.importer.socrata.SocrataApi).%New()

SET api = ##CLASS(dc.dataset.importer.socrata.SocrataApi).%New()
^
<CLASS DOES NOT EXIST> *dc.dataset.importer.socrata.SocrataApi
IRISAPP>
````

class is also missing in Repo

**Comment by jrpereirajr** [comment]
Hi @rcemper!
Thank you for point me this out! I did some refactoring and missed the project description...
I updated the README and now the guide works as expected.

**Comment by rcemper** [comment]
still pending in README
but
**set api = ##class(dc.dataset.importer.socrata.SocrataApi).%New() worked**
README requires adjustment
