### ISSUE TITLE
Create a Dataset table

### ISSUE THREAD

**Issue by eduard93** [diashenrique/iris-kaggle-socrata-generator#3]
To remove discovery-via-Postman step maybe it's possible to add an autogenerated "Dataset" table containing names/descriptions/datasetId of all datasets?

**Comment by jrpereirajr** [comment]
Hi @eduard93! Thank you for your feedback!
@diashenrique is finishing a UI for easy quering and installation of datasets.

**Comment by diashenrique** [comment]
@eduard93 I just released the UI for Socrata. 
Could you check if the interface meets your requirements?

**Comment by jrpereirajr** [comment]
Hi @eduard93.
We also just released the Kaggle datasets search feature in the UI.
I'll close this issue but fell free to reopen it.

**Comment by eduard93** [comment]
Thanks!
