### ISSUE TITLE
Outdated image reference in Dockerfile?

### ISSUE THREAD

**Issue by bdeboe** [diashenrique/iris-kaggle-socrata-generator#4]
I had trouble building the docker image with the current Dockerfile, with it complaining about an invalid license (which may be due to it having expired recently, it was a 2020.1 one after all)

Using the following line worked
```
ARG IMAGE=intersystemsdc/iris-ml-community:2021.2.0.617.0-zpm
```

This upgrade also meant I had to replace "irisuser" with "irisowner" in some of the Dockerfile's other commands

better get this sorted to keep your bonus ;-)

**Comment by bdeboe** [comment]
hmm, maybe that still wasn't good enough, or my changes triggered something else. 
Now the container keeps restarting and when I disable it in docker-compose.xml I get this:

```
PS C:\Users\bdeboe\GitHub\contest\iris-rad-studio> docker-compose up
Creating network "iris-rad-studio_default" with the default driver
Creating iris-rad-studio_iris_1 ... done
Attaching to iris-rad-studio_iris_1
iris_1  | [INFO] Executing command /home/irisowner/irissys/startISCAgent.sh 2188...
iris_1  | [INFO] Writing status to file: /home/irisowner/irissys/iscagent.status
iris_1  | Reading configuration from file: /home/irisowner/irissys/iscagent.conf
iris_1  | ISCAgent[19]: Starting
iris_1  | ISCAgent[20]: Starting ApplicationServer on *:2188
iris_1  | [INFO] ...executed command /home/irisowner/irissys/startISCAgent.sh 2188
iris_1  | [INFO] Starting InterSystems IRIS instance IRIS...
iris_1  | [INFO] Invalid registry ownership
iris_1  | [ERROR] Command "iris start IRIS quietly" exited with status 256
iris_1  | [ERROR] See the above messages or /usr/irissys/mgr/messages.log for more information
iris_1  | [FATAL] Error starting InterSystems IRIS
iris-rad-studio_iris_1 exited with code 1
```

(FWIW, this image worked fine for another contest submission)

I'll switch to ZPM

**Comment by diashenrique** [comment]
HI @bdeboe 
We didn't experience anything similar. We'll try to simulate this behavior. 
Just a comment, the IRIS RAD Studio it's one of our old projects.

**Comment by jrpereirajr** [comment]
Hi @bdeboe.
I tried build the image with no problems.
As @diashenrique pointed, may be you used a other project image.
I'll close this issue, but fell free to reopen it.

**Comment by bdeboe** [comment]
then the issue becomes: fix the git link in the readme file 😛

**Comment by jrpereirajr** [comment]
You're right @bdeboe! 
Sorry, I didn't noted that the instructions text was wrong... :/
Text fixed, thanks for warning us! :)
